pipeline {
    agent {
        docker { image 'python:3.12' }
    }
    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', credentialsId: 'my-credentials-id', url: 'https://github.com/ForeverCountry/alx-backend-python.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                sh 'pip3 install -r messaging_app/requirements.txt'
            }
        }
        stage('Run Tests') {
            steps {
                sh 'pytest messaging_app --junitxml=report.xml'
            }
        }
        stage('Archive Test Results') {
            steps {
                junit 'report.xml'
            }
        }
    }
}
